version: '3.8'  #version của Docker Compose

services:
  postgres:
    image: postgres:15
    container_name: mini_app_postgres
    restart: always
    environment:
      POSTGRES_USER: thanhcn3
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: MiniApp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: mini_app_mongodb  # Đổi tên container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: thanhcn3
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: mini_app_redis  # Đổi tên container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: